- name: Setup Dependencies
  hosts: all
  become: yes
  roles:
    - geerlingguy.docker
    - gitlab-runner
  tasks:
   - name: Update apt cache
     shell: |
      apt update
      apt upgrade -y
   - name: Install OpenVpn
     ansible.builtin.apt:
      name: "openvpn"
      state: present
      update_cache: true
      update_cache_retries: 3
  
