- name: Setup Dependencies
  hosts: all
  become: yes
  roles:
    - role: java
      tags: java
      when:
        - ansible_os_family == 'Debian'
      vars:
        java_packages:
          - openjdk-21-jdk
    - role: maven
      vars:
        maven_version: '3.9.4'
      tags: maven
    - role: gitlab-runner
      tags: gitlab-runner
    - role: geerlingguy.docker
      tags: docker
  tasks:
   - name: Update apt cache
     shell: |
      apt update
      apt upgrade -y
   - name: Install OpenVpn
     ansible.builtin.apt:
      name: "openvpn"
      state: present
      update_cache: true
      update_cache_retries: 3
  
